language: java
jdk:
- oraclejdk8
install: true
script: mvn clean install
before_install:
- openssl aes-256-cbc -K $encrypted_c54118c7b134_key -iv $encrypted_c54118c7b134_iv
  -in App.java.enc -out App.java -d
